In [ ]:
import matplotlib.pyplot as plt

img = plt.imread("/home/ved/Ved/Project_1/RF-3DGS/data/RF-3DGS_dataset/RF-3DGS_trained_RRF/3dgs_Delay_100/test/ours_40000/renders/00000.png")

print(f"Image shape: {img.shape}")
print(f"Image pixel value range: {img}")

Image shape: (154, 231, 3)
Image pixel value range: [[[0.2901961  0.78039217 0.78039217]
  [0.2901961  0.7764706  0.7764706 ]
  [0.2901961  0.7764706  0.7764706 ]
  ...
  [0.10196079 0.49803922 0.49803922]
  [0.10588235 0.5137255  0.5137255 ]
  [0.11372549 0.5372549  0.5372549 ]]

 [[0.29411766 0.78039217 0.78039217]
  [0.2901961  0.7764706  0.7764706 ]
  [0.2901961  0.7764706  0.7764706 ]
  ...
  [0.11372549 0.5137255  0.5137255 ]
  [0.12156863 0.5411765  0.5411765 ]
  [0.13725491 0.5686275  0.5686275 ]]

 [[0.29411766 0.78039217 0.78039217]
  [0.29411766 0.78039217 0.78039217]
  [0.2901961  0.7764706  0.7764706 ]
  ...
  [0.13333334 0.5529412  0.5529412 ]
  [0.15294118 0.5882353  0.5882353 ]
  [0.18431373 0.63529414 0.63529414]]

 ...

 [[0.2627451  0.8039216  0.8039216 ]
  [0.2627451  0.8039216  0.8039216 ]
  [0.2627451  0.8039216  0.8039216 ]
  ...
  [0.24313726 0.7490196  0.7490196 ]
  [0.24313726 0.7490196  0.7490196 ]
  [0.24313726 0.7490196  0.7490196 ]]

 [[0.2627451  0.803921

In [53]:
import matplotlib.pyplot as plt
import numpy as np

img_gt = plt.imread("/home/ved/Ved/Project_1/RF-3DGS/output/rf_model/test/ours_40000/gt/00000.png")
img = plt.imread("/home/ved/Ved/Project_1/RF-3DGS/output/rf_model/test/ours_40000/renders/00000.png")

print(f"Image shape: {img_gt.shape}")
# print(f"Image pixel value range: {img_gt}")
img_diff = img_gt - img
img_diff = np.abs(img_diff)
print(f"Difference image shape: {img_diff.max(), img_diff.min()}")
print(img_diff)

Image shape: (600, 600, 3)
Difference image shape: (np.float32(1.0), np.float32(0.0))
[[[0.29019606 0.00784314 0.09019609]
  [0.29019606 0.01176471 0.09019609]
  [0.2862745  0.01568627 0.08627452]
  ...
  [0.2588235  0.01176471 0.22352941]
  [0.26274508 0.         0.24705882]
  [0.27058822 0.         0.25882354]]

 [[0.28235292 0.00392157 0.09019609]
  [0.2862745  0.00784314 0.09019609]
  [0.28235292 0.01176471 0.09019609]
  ...
  [0.26274508 0.         0.25490198]
  [0.26666665 0.         0.2627451 ]
  [0.27058822 0.         0.24705884]]

 [[0.27843136 0.         0.08627452]
  [0.27843136 0.00392157 0.08627452]
  [0.27843136 0.00392157 0.08627452]
  ...
  [0.26666665 0.         0.27058825]
  [0.26274508 0.         0.25490198]
  [0.27058822 0.01568627 0.227451  ]]

 ...

 [[0.00784314 0.00392157 0.01960784]
  [0.02745098 0.01568627 0.05098039]
  [0.05490196 0.02352941 0.07450981]
  ...
  [0.03137258 0.03529412 0.02352941]
  [0.05490199 0.03921568 0.05098039]
  [0.09411767 0.04313725 0.

In [31]:
import numpy as np
import matplotlib.pyplot as plt

# Load saved grayscale image
img = plt.imread("/home/ved/Ved/Project_1/RF-3DGS/output/rf_model/test/ours_40000/renders/00001.png")  # values in [0,1] if saved properly
print(f"Image shape after channel check: {img.shape}")
print(f"Image pixel value range: min={img.min()}, max={img.max()}")
# If image has 3 channels (RGB), convert to single channel
if img.ndim == 3:
    img = img[..., 0]
print(f"Image shape after channel check: {img.shape}")
print(f"Image pixel value range: min={img.min()}, max={img.max()}")

Image shape after channel check: (600, 600, 3)
Image pixel value range: min=0.0, max=1.0
Image shape after channel check: (600, 600)
Image pixel value range: min=0.5372549295425415, max=1.0


In [27]:
import numpy as np
import matplotlib.pyplot as plt

# Load saved grayscale image
img = plt.imread("/home/ved/Ved/Project_1/RF-3DGS/output/rf_model_gray/test/ours_40000/renders/00000.png")  # values in [0,1] if saved properly

# If image has 3 channels (RGB), convert to single channel
if img.ndim == 3:
    img = img[..., 0]
print(f"Image shape after channel check: {img.shape}")
print(f"Image pixel value range: min={img.min()}, max={img.max()}")
# Given global normalization values
spec_min = -127.66157392032275
spec_max = -47.837825100272184

# Inverse normalization
spec_recovered = img * (spec_max - spec_min) + spec_min
print(f"Recovered spectrum value range: min={spec_recovered.min()}, max={spec_recovered.max()}")
print(f"Recovered spectrum values (sample): {spec_recovered}")

Image shape after channel check: (600, 600)
Image pixel value range: min=0.16470588743686676, max=0.8588235378265381
Recovered spectrum value range: min=-114.5141372680664, max=-59.10706329345703
Recovered spectrum values (sample): [[-79.45429  -79.76733  -79.76733  ... -79.45429  -79.76733  -79.76733 ]
 [-79.45429  -79.45429  -79.76733  ... -79.45429  -79.76733  -79.76733 ]
 [-79.14126  -79.45429  -79.45429  ... -79.45429  -79.76733  -79.76733 ]
 ...
 [-87.593185 -86.34105  -87.593185 ... -89.158356 -89.47139  -88.53229 ]
 [-86.34105  -87.28015  -87.593185 ... -89.158356 -89.784424 -89.158356]
 [-87.28015  -87.593185 -87.593185 ... -89.158356 -89.784424 -89.47139 ]]


In [1]:
import matplotlib.pyplot as plt
import numpy as np

import os
import tensorflow as tf
from sionna.rt import load_scene, Transmitter, Receiver, PlanarArray, RadioMaterial
import sionna

2026-02-12 12:07:55.001930: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-02-12 12:07:55.025762: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-02-12 12:07:55.891875: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2026-02-12 12:07:55.89

In [9]:
# --- 1. GPU Setup (Optional but recommended) ---
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    try:
        tf.config.experimental.set_memory_growth(gpus[0], True)
    except RuntimeError as e:
        print(e)

# Load the scene
scene_path = '/tf/Project_1/test.xml'

print(f"Loading scene from: {scene_path}")
scene = load_scene(scene_path)

# Configure the scene for ray tracing
scene.frequency = 2.4e9  # 2.4 GHz (WiFi frequency)
scene.synthetic_array = True
wavelength = 299792458 / scene.frequency

print("✓ Scene loaded and configured.")
print(f"Objects in scene: {list(scene.objects.keys())}")

scene.preview(show_devices=True)

Loading scene from: /tf/Project_1/test.xml
✓ Scene loaded and configured.
Objects in scene: ['floor', 'window', 'door', 'furniture', 'furniture_center', 'led_tv', 'metallic_cube']


Renderer(camera=PerspectiveCamera(aspect=1.31, children=(DirectionalLight(intensity=0.25, position=(0.0, 0.0, …

In [13]:

    
    # --- 3. Configure Materials (Crucial for seeing reflections) ---
    # We must re-apply materials because the XML only contains geometry
    global_scattering_coeff = 4
    
    # Define Materials
    mat_concrete = RadioMaterial("mat_concrete_scat", relative_permittivity=5.24, conductivity=0.0462, scattering_coefficient=0.1*global_scattering_coeff)
    mat_wood = RadioMaterial("mat_wood_scat", relative_permittivity=1.99, conductivity=0.0047, scattering_coefficient=0.2*global_scattering_coeff)
    mat_glass = RadioMaterial("mat_glass_scat", relative_permittivity=6.31, conductivity=0.0036, scattering_coefficient=0.025*global_scattering_coeff)
    mat_metal = RadioMaterial("mat_metal_scat", relative_permittivity=1, conductivity=1e7, scattering_coefficient=0.025*global_scattering_coeff)

    # Add to scene dictionary
    for mat in [mat_concrete, mat_wood, mat_glass, mat_metal]:
        if mat.name not in scene.radio_materials:
            scene.add(mat)

    # Assign to Objects
    for obj_name, obj in scene.objects.items():
        name = obj_name.lower()
        if "floor" in name or "walls" in name or "ceiling" in name or "pillar" in name:
            obj.radio_material = "mat_concrete_scat"
        elif "furniture" in name or "door" in name:
            obj.radio_material = "mat_wood_scat"
        elif "window" in name:
            obj.radio_material = "mat_glass_scat"
        elif "tv" in name or "led" in name or "metallic_cube" in name:
            obj.radio_material = "mat_metal_scat"

In [11]:


    # --- 4. Setup Antenna Arrays ---
    scene.tx_array = PlanarArray(num_rows=1, num_cols=1, pattern="iso", polarization="V",
                                 vertical_spacing=0.5*wavelength, horizontal_spacing=0.5*wavelength)
    scene.rx_array = PlanarArray(num_rows=1, num_cols=1, pattern="iso", polarization="V",
                                 vertical_spacing=0.5*wavelength, horizontal_spacing=0.5*wavelength)

    # --- 5. Place Devices (The "Sloped V" Configuration) ---
    
    # A. Transmitter (High up)
    tx_pos = [2.5, 1.5, 2.5]
    if 'tx' in scene.objects: scene.remove('tx')
    tx = Transmitter(name="tx", position=tx_pos)
    scene.add(tx)

    # B. Receivers (Waist height)
    # We add BOTH so you can see the V-shape simultaneously
    
    # Rx 1: The Diagonal
    rx1_pos = [6.7, 2.5, 1.5]
    rx1 = Receiver(name="rx_diagonal", position=rx1_pos)
    scene.add(rx1)

    # Rx 2: The Side Flank
    rx2_pos = [0.3, 2.2, 1.5]
    rx2 = Receiver(name="rx_flank", position=rx2_pos)
    scene.add(rx2)

   

In [14]:
 # --- 6. Compute Rays (Lighter settings for Visualization) ---
print("Computing Ray Paths...")
paths = scene.compute_paths(
    max_depth=2,
    num_samples=int(1e6), # 200k samples is a good balance for viz speed
    reflection=True, 
    diffraction=True, 
    scattering=True,
    scat_keep_prob=0.01
)
print("Computed")



Computing Ray Paths...
Computed


In [15]:
    # --- 7. Interactive Render ---
    print("rendering scene...")
    # This line generates the interactive widget in Jupyter
    scene.preview(paths=paths, show_devices=True, show_paths=True, resolution=[800, 600])

rendering scene...


Renderer(camera=PerspectiveCamera(aspect=1.3333333333333333, children=(DirectionalLight(intensity=0.25, positi…

# Sionna Ray Tracing Visualization

This notebook loads the room scene with tables, chairs, door, and window, then performs ray tracing visualization with Sionna.

In [ ]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf
from sionna.rt import load_scene, Camera, Transmitter, Receiver, PlanarArray
import matplotlib.pyplot as plt
import IPython.display

In [ ]:
# Load the scene
scene_path = '/tf/Project_1/room_with_cube.xml'

print(f"Loading scene from: {scene_path}")
scene = load_scene(scene_path)

# Configure the scene for ray tracing
scene.frequency = 2.4e9  # 2.4 GHz (WiFi frequency)
scene.synthetic_array = True

print("✓ Scene loaded and configured.")
print(f"Objects in scene: {list(scene.objects.keys())}")

scene.preview(show_devices=False)

In [ ]:
# Assign radio materials for RF simulation
print("Assigning radio materials...")
print(f"Available objects in scene: {list(scene.objects.keys())}")

# Map XML IDs to Sionna Radio Materials
# Based on your XML: 
# - 'mat_white' (walls, ceiling, pillar) -> itu_concrete
# - 'mat_wood' (furniture, door, furniture_center) -> itu_wood
material_map = {
    'floor': 'itu_concrete',
    'ceiling': 'itu_concrete',        # or 'itu_plasterboard' if it's a false ceiling
    'walls': 'itu_concrete',
    'pillar': 'itu_concrete',
    'window': 'itu_glass',
    'door': 'itu_wood',
    'furniture': 'itu_wood',
    'furniture_center': 'itu_wood',   # <--- Added this (was missing)
    'led_tv': 'itu_metal'
}

assigned = []
for obj_name, material in material_map.items():
    obj = scene.get(obj_name)
    if obj is not None:
        obj.radio_material = material
        assigned.append(f"  - {obj_name}: {material.replace('itu_', '')}")
    else:
        # This helps debug if there's a typo in the XML ID
        print(f"  ⚠ Warning: Object '{obj_name}' defined in map but not found in scene")

print("✓ Materials assigned successfully:")
for msg in assigned:
    print(msg)

In [ ]:
# Add a camera for visualization
# Room: 5m(x) x 3m(y) x 3m(z)
# Position camera inside room, looking at center
cam_pos = [1.0, 1.5, 2.0]  # Inside the room
cam_look_at = [2.5, 1.5, 1.0]  # Looking at center area
camera = Camera("viz_camera", position=cam_pos, look_at=cam_look_at)
scene.add(camera)
print(f"✓ Camera added at {cam_pos}, looking at {cam_look_at}")

In [ ]:
# Configure antenna arrays for transmitter and receiver
scene.tx_array = PlanarArray(num_rows=1, num_cols=1, 
                            vertical_spacing=0.5, 
                            horizontal_spacing=0.5, 
                            pattern="iso", 
                            polarization="V")

scene.rx_array = PlanarArray(num_rows=1, num_cols=1, 
                            vertical_spacing=0.5, 
                            horizontal_spacing=0.5, 
                            pattern="iso", 
                            polarization="V")

# Add transmitter (near ceiling)
tx_pos = [2.5, 1.5, 2.8]
tx = Transmitter("tx", tx_pos)
scene.add(tx)

# Add receiver (near table level)
rx_pos = [1.0, 0.5, 0.8]
rx = Receiver("rx", rx_pos)
scene.add(rx)

print(f"✓ Transmitter at {tx_pos}")
print(f"✓ Receiver at {rx_pos}")

In [ ]:
# Compute ray paths for RF propagation analysis
print("\nComputing ray paths...")
paths = scene.compute_paths(max_depth=3, num_samples=1e6)

print(f"✓ Ray tracing complete")
print(f"Number of paths computed: {paths.mask.shape}")
print(f"Path types captured: Reflection, Diffraction, Scattering")

In [ ]:
# Visualize paths in 3D
print("Generating 3D ray visualization...")
scene.preview(paths=paths, show_devices=True, show_paths=True)